Repository fastcam-sideproject/BE-master-plan-b, pull requests merged in 2025-02, with the labels that each got.

#52 Refactor/post
  src/main/java/com/example/masterplanbbe/domain/comment/controller/CommentController.java
  src/main/java/com/example/masterplanbbe/domain/comment/dto/CommentDto.java
  src/main/java/com/example/masterplanbbe/domain/comment/dto/CommentRequest.java
  src/main/java/com/example/masterplanbbe/domain/comment/dto/CommentResponse.java
  src/main/java/com/example/masterplanbbe/domain/comment/service/CommentService.java
  src/main/java/com/example/masterplanbbe/domain/post/controller/PostController.java
  src/main/java/com/example/masterplanbbe/domain/post/dto/PostDto.java
  src/main/java/com/example/masterplanbbe/domain/post/dto/PostRequest.java
  src/main/java/com/example/masterplanbbe/domain/post/dto/PostResponse.java
  src/main/java/com/example/masterplanbbe/domain/post/entity/Post.java
  src/main/java/com/example/masterplanbbe/domain/post/service/PostService.java
  src/test/java/com/example/masterplanbbe/domain/post/service/PostServiceTest.java
Labels: 리팩토링, 기능 추가, 테스트

#57 회원 시험 일정 수정 기능
  src/main/java/com/example/masterplanbbe/common/exception/ErrorCode.java
  src/main/java/com/example/masterplanbbe/domain/userExamSession/controller/UserExamSessionController.java
  src/main/java/com/example/masterplanbbe/domain/userExamSession/dto/request/UserExamSessionCreateRequest.java
  src/main/java/com/example/masterplanbbe/domain/userExamSession/dto/request/UserExamSessionRequest.java
  src/main/java/com/example/masterplanbbe/domain/userExamSession/entity/UserExamSession.java
  src/main/java/com/example/masterplanbbe/domain/userExamSession/repository/UserExamSessionRepositoryAdapter.java
  src/main/java/com/example/masterplanbbe/domain/userExamSession/repository/UserExamSessionRepositoryPort.java
  src/main/java/com/example/masterplanbbe/domain/userExamSession/service/UserExamSessionService.java
Labels: 기능 추가

#58 회원 시험 일정 삭제 기능
  src/main/java/com/example/masterplanbbe/domain/userExamSession/controller/UserExamSessionController.java
  src/main/java/com/example/masterplanbbe/domain/userExamSession/repository/UserExamSessionRepository.java
  src/main/java/com/example/masterplanbbe/domain/userExamSession/repository/UserExamSessionRepositoryAdapter.java
  src/main/java/com/example/masterplanbbe/domain/userExamSession/repository/UserExamSessionRepositoryPort.java
  src/main/java/com/example/masterplanbbe/domain/userExamSession/service/UserExamSessionService.java
Labels: 기능 추가

#59 회원 시험 일정 상세 조회 기능
  src/main/java/com/example/masterplanbbe/domain/userExamSession/controller/UserExamSessionController.java
  src/main/java/com/example/masterplanbbe/domain/userExamSession/dto/response/UserExamSessionDetailResponse.java
  src/main/java/com/example/masterplanbbe/domain/userExamSession/repository/UserExamSessionRepositoryAdapter.java
  src/main/java/com/example/masterplanbbe/domain/userExamSession/repository/UserExamSessionRepositoryPort.java
  src/main/java/com/example/masterplanbbe/domain/userExamSession/service/UserExamSessionService.java
Labels: 기능 추가

#61 Feat/authentication:: 스프링 시큐리티, Redis 기반 기본 인증 및 인가 로직 구축
  build.gradle
  src/main/java/com/example/masterplanbbe/common/GlobalExceptionHandler.java
  src/main/java/com/example/masterplanbbe/common/config/RedisConfig.java
  src/main/java/com/example/masterplanbbe/common/exception/ErrorCode.java
  src/main/java/com/example/masterplanbbe/common/response/ApiResponse.java
  src/main/java/com/example/masterplanbbe/common/response/ErrorResponse.java
  src/main/java/com/example/masterplanbbe/member/controller/MemberController.java
  src/main/java/com/example/masterplanbbe/member/dto/MemberCreateRequest.java
  src/main/java/com/example/masterplanbbe/member/dto/MemberResponse.java
  src/main/java/com/example/masterplanbbe/member/dto/MemberUpdateRequest.java
  src/main/java/com/example/masterplanbbe/member/entity/Member.java
  src/main/java/com/example/masterplanbbe/member/entity/MemberRoleEnum.java
  src/main/java/com/example/masterplanbbe/member/exception/DuplicateUserException.java
  src/main/java/com/example/masterplanbbe/member/repository/MemberRepository.java
  src/main/java/com/example/masterplanbbe/member/repository/MemberRepositoryAdapter.java
  src/main/java/com/example/masterplanbbe/member/repository/MemberRepositoryPort.java
  src/main/java/com/example/masterplanbbe/member/service/MemberService.java
  src/main/java/com/example/masterplanbbe/member/service/response/MemberResponse.java
  src/main/java/com/example/masterplanbbe/security/config/SecurityConfig.java
  src/main/java/com/example/masterplanbbe/security/dto/LoginDTO.java
  src/main/java/com/example/masterplanbbe/security/dto/MemberInfoDTO.java
  src/main/java/com/example/masterplanbbe/security/exception/CustomAuthenticationException.java
  src/main/java/com/example/masterplanbbe/security/exception/JwtAccessDenyHandler.java
  src/main/java/com/example/masterplanbbe/security/exception/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/masterplanbbe/security/filter/CustomLoginFilter.java
  src/main/java/com/example/masterplanbbe/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/example/masterplanbbe/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/example/masterplanbbe/security/handler/CustomLogoutHandler.java
  src/main/java/com/example/masterplanbbe/security/jwt/JwtService.java
  src/main/java/com/example/masterplanbbe/security/jwt/TokenPayload.java
  src/main/java/com/example/masterplanbbe/security/jwt/TokenUtils.java
  src/main/java/com/example/masterplanbbe/security/uri/PassableUris.java
  src/main/java/com/example/masterplanbbe/security/user/UserDetailsImpl.java
  src/main/java/com/example/masterplanbbe/security/user/UserDetailsServiceImpl.java
  src/test/java/com/example/masterplanbbe/member/api/MemberApiTest.java
Labels: 기능 추가

#67 Feat/authentication::스프링 시큐리티 토큰 블랙리스트 처리 기능 추가
  src/main/java/com/example/masterplanbbe/common/config/RedisConfig.java
  src/main/java/com/example/masterplanbbe/common/exception/ErrorCode.java
  src/main/java/com/example/masterplanbbe/security/handler/CustomLogoutHandler.java
  src/main/java/com/example/masterplanbbe/security/jwt/JwtService.java
Labels: 리팩토링, 기능 추가

#72 feat: 게시글 좋아요 Redis도입
  src/main/java/com/example/masterplanbbe/common/config/RedisConfig.java
  src/main/java/com/example/masterplanbbe/domain/post/entity/Post.java
  src/main/java/com/example/masterplanbbe/domain/post/service/PostLikeService.java
  src/test/java/com/example/masterplanbbe/domain/post/service/PostLikeServiceTest.java
Labels: 리팩토링, 기능 추가
